version: '3.8'

services:
  db:
    image: order_service:latest
    container_name: order_service
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: mydatabase
    ports:
      - "6543:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
